### PR TITLE
Rework `enforce_element_constraints`

### LINKED ISSUE #12: Refactor `enforce_element_constraints`
It would be good to split `enforce_element_constraints` into two functions: (a) a function which enforces the (possibly spatially varying) constraints on a single metric and lives in Animate; (b) a function for handling doing this over a `MeshSeq`, which lives here.

### PR DESCRIPTION
**Pull request by jwallwork23**
Closes #12.
See PR https://github.com/pyroteus/animate/pull/38.

Here we rename `enforce_element_constraints` as `enforce_variable_constraints` and make use of the new functionality in Animate.

Tests still need to be added.

### CODE REVIEW

**Comment by jwallwork23** [comment]
Partially addresses #121.

**Comment by jwallwork23** [comment]
Okay it's now ready for review @ddundo

**Comment by jwallwork23** [comment]
Would you mind taking a look at this @ddundo? The changes should be fairly non-controversial.

**Review by ddundo — CHANGES_REQUESTED** [review]
Sorry @jwallwork23, I forgot about this! Looks good, but I had some tests fail locally so I re-ran the CI and got the same here.

**Comment by jwallwork23** [comment]
> Sorry @jwallwork23, I forgot about this! Looks good, but I had some tests fail locally so I re-ran the CI and got the same here.

I just merged in `main` so hopefully that fixes things.

**Comment by ddundo** [comment]
@jwallwork23 sorry, I don't know if you were waiting for a response from me here :) it looks good to me now!

**Comment by jwallwork23** [comment]
> @jwallwork23 sorry, I don't know if you were waiting for a response from me here :) it looks good to me now!

Please can you approve? Otherwise I can't merge.

**Review by ddundo — APPROVED** [review]
Done :)

**Pull request merged**
